export const portfolioItems = [
  {
    id: "1",
    title: "Seraph Station",
    year: "September 2019",
    image: "https://i.postimg.cc/Pqpr43Qf/image-seraph.jpg",
    mobileImage: "https://i.postimg.cc/pdn5qGFv/image-seraph.jpg",
  },
  {
    id: "2",
    title: "Eebox Building",
    year: "August 2017",
    image: "https://i.postimg.cc/0yHy7RmH/image-eebox.jpg",
    mobileImage: "https://i.postimg.cc/HsBMx7gq/image-eebox.jpg",
  },
  {
    id: "3",
    title: "Federal II Tower",
    year: "March 2017",
    image: "https://i.postimg.cc/52ttHNHC/image-federal.jpg",
    mobileImage: "https://i.postimg.cc/fRP07nk5/image-federal.jpg",
  },
  {
    id: "4",
    title: "Project Del So",
    year: "January 2016",
    image: "https://i.postimg.cc/zXqbNd3f/image-del-sol.jpg",
    mobileImage: "https://i.postimg.cc/8zXNmJ2Q/image-del-sol-mob.jpg",
  },
  {
    id: "5",
    title: "Le Prototype",
    year: "October 2015",
    image: "https://i.postimg.cc/rFgdwStN/image-prototype.jpg",
    mobileImage: "https://i.postimg.cc/cJKZ91WK/image-prototype-mob.jpg",
  },
  {
    id: "6",
    title: "228B Tower",
    year: "April 2015",
    mobileImage: "https://i.postimg.cc/7ZZqzMQn/image-228b-mob.jpg",
  },
  {
    id: "7",
    title: "Grand Edelweiss Hotel",
    year: "December 2013",
    image: "https://i.postimg.cc/5NbyVmbp/image-edelweiss.jpg",
    mobileImage: "https://i.postimg.cc/T1cDnKWW/image-edelweiss.jpg",
  },
  {
    id: "8",
    title: "Netcry Tower",
    year: "August 2012",
    image: "https://i.postimg.cc/nrtzM47F/image-netcry.jpg",
    mobileImage: "https://i.postimg.cc/wT6JgQS5/image-netcry.jpg",
  },
  {
    id: "9",
    title: "Hypers",
    year: "January 2012",
    image: "https://i.postimg.cc/VvBNtJBj/image-hypers.jpg",
    mobileImage: "https://i.postimg.cc/5yJzHBjV/image-hypers.jpg",
  },
  {
    id: "10",
    title: "SXIV Tower",
    year: "March 2011",
    image: "https://i.postimg.cc/NG1FSnq5/image-sxiv.jpg",
    mobileImage: "https://i.postimg.cc/P5Jw8rfP/image-sxiv.jpg",
  },
  {
    id: "11",
    title: "Trinity Bank Tower",
    year: "September 2010",
    image: "https://i.postimg.cc/gksJk60p/image-trinity.jpg",
    mobileImage: "https://i.postimg.cc/2jdvsKX8/image-trinity.jpg",
  },
  {
    id: "12",
    title: "Project Paramour",
    year: "February 2008",
    image: "https://i.postimg.cc/RFthMsWp/image-paramour.jpg",
    mobileImage: "https://i.postimg.cc/nzB7cRF2/image-paramour.jpg",
  },
]
